name: rtd38
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - openbabel=3.1.1
  - mock
  - pillow
  - sphinx==3.4.3
  - sphinx_rtd_theme
  - pip>=20.1  # pip is needed as dependency
  - pandoc
  - pip:
    - jinja2==3.0.3
    - numpy
    - tensorflow-cpu
    - scipy
    - matplotlib
    - pandas
    - scikit-learn
    - pyyaml
    - rdkit  # Or via channels rdkit and conda rdkit
    - tensorflow_addons
    - pymatgen
    - pyxtal
    - ase
    - ipython
    - nbsphinx
    - click
    - pyxtal